# k8s/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Each key from your .env file must be listed here
  # The values MUST be Base64 encoded
  MONGO_URI: "bW9uZ29kYitzcnY6Ly9oZWFsdGhIYWNrOmlMc2tLbTJxckJsTUYyYWVAaGVhbHRoaGFjay41bm9hei5tb25nb2RiLm5ldC9oZWFsdGhEQg=="
  GEMINI_API_KEY: "QUl6YVN5QUxuMFBfZmI4TF9aNGoxOHQ3M21zbWJDWm9MVklkbndJ"
  PORT: "ODAwMA=="
  JWT_SECRET: "aGVhbHRoSGFjaw=="
  EMAIL_USER: "dnlhc2FuYW5kMDAwN0BnbWFpbC5jb20="
  EMAIL_PASS: "d3pxY29yeHF5a29leWp5Zw=="
